config/routes.rb
Rails.application.routes.draw do

  root 'adverts#index'

  resources :adverts do
    collection do
      get 'search'
    end
  end

end

app/models/advert.rb
class Advert < ActiveRecord::Base
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @search = Advert.search(params[:q])
    @adverts = @search.result(distinct: true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:title, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adverts/_form.html.erb
<%= form_for(@advert) do |f| %>
  <% if @advert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advert.errors.count, "error") %> prohibited this advert from being saved:</h2>

      <ul>
      <% @advert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adverts/edit.html.erb
<h1>Editing Advert</h1>

<%= render 'form' %>

<%= link_to 'Show', @advert %> |
<%= link_to 'Back', adverts_path %>

app/views/adverts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adverts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adverts.each do |advert| %>
      <tr>
        <td><%= advert.title %></td>
        <td><%= advert.content %></td>
        <td><%= link_to 'Show', advert %></td>
        <td><%= link_to 'Edit', edit_advert_path(advert) %></td>
        <td><%= link_to 'Destroy', advert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advert', new_advert_path %>

app/views/adverts/new.html.erb
<h1>New Advert</h1>

<%= render 'form' %>

<%= link_to 'Back', adverts_path %>

app/views/adverts/search.html.erb
<% @adverts.each do |advert| %>
  <p>
    <strong>Title:</strong>
    <%= advert.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= advert.content %>
  </p>
  <br>
<% end %>

<%= link_to 'Home', adverts_path %>

app/views/adverts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @advert.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @advert.content %>
</p>

<%= link_to 'Edit', edit_advert_path(@advert) %> |
<%= link_to 'Back', adverts_path %>
</br>
<%= link_to 'similar jobs', search_adverts_path(q: {title_cont_any: @advert.title.split(' ')}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RansackSearchInLink</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>